version: "3.6"

networks:
  skynet:
    driver: bridge
    attachable: true

volumes:
  so1-var:
  so1-etc:

services:
  so1:
    networks:
      skynet:
        aliases:
          - so1
    image: splunk/splunk:latest
    container_name: so1
    restart: always
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunk58
      - DEBUG=true
      - SPLUNK_UPGRADE=true
    ports:
      - 8000:8000
      - 8088:8088
    volumes:
      - so1-var:/opt/splunk/var
      - so1-etc:/opt/splunk/etc
